server:
  port: 38080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: LFMP-BackEnd
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3300/lfmp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  level:
    com.MinNiCup.lfmpbackend.mapper: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
